/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cl.sudamerican.roman;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static org.junit.jupiter.api.Assertions.assertEquals;

class RomanNumeralsShould {
    private RomanNumerals romanNumerals;

    @BeforeEach
    void setUp() {
        romanNumerals = new RomanNumerals();
    }

    @Test
    void return_string_when_passing_number() {
        assertEquals("", romanNumerals.convert(0));
        assertEquals("I", romanNumerals.convert(1));
        assertEquals("II", romanNumerals.convert(2));
        assertEquals("III", romanNumerals.convert(3));
        assertEquals("IV", romanNumerals.convert(4));
        assertEquals("V", romanNumerals.convert(5));
        assertEquals("VI",romanNumerals.convert(6));
        assertEquals("VII",romanNumerals.convert(7));
        assertEquals("VIII",romanNumerals.convert(8));
        assertEquals("IX",romanNumerals.convert(9));
    }

}
